# Generated by Django 5.0.6 on 2024-05-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turfname', models.CharField(max_length=80)),
                ('turfarea', models.CharField(max_length=80)),
                ('turfpic', models.ImageField(upload_to='')),
            ],
        ),
    ]
