# Generated by Django 5.0.6 on 2024-05-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='turfpic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
