# Generated by Django 5.0.6 on 2024-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_turf_turfpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='turfrate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
