# Generated by Django 5.0.6 on 2024-05-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_turf_turfrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_name', models.CharField(max_length=100)),
                ('register_id', models.CharField(max_length=100)),
                ('register_mobile', models.CharField(max_length=20)),
                ('register_address', models.CharField(max_length=300)),
                ('register_mobile2', models.CharField(max_length=20)),
                ('turfname', models.CharField(max_length=80)),
                ('date', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=20)),
                ('timings', models.CharField(max_length=30)),
            ],
        ),
    ]
