# Generated by Django 5.0.6 on 2024-06-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
    ]
